spring:
  application:
    name: find-my-edge

  datasource:
    url: jdbc:mysql://localhost:3306/find_my_edge
    username: root
    password: Ansh@2004

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  jackson:
    time-zone: Asia/Kolkata

dhan:
  base-url: ${DHAN_BASE_URL:https://api.dhan.co}
  auth-url: ${DHAN_AUTH_URL:https://auth.dhan.co}
  client-id: ${DHAN_CLIENT_ID}
  app-id: ${DHAN_APP_ID}
  app-secret: ${DHAN_APP_SECRET}

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}